<?php
	$helper = $this->_retailerkittoolHelper; 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
	$formKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
?>
<style type="text/css">
.label {
    margin-bottom: -50px;
    padding-left: 5px;
    padding-top: 2px;
    position: absolute;
    color: #908f8f;    
    z-index: 999;
    opacity: 0;
    font-weight: 100;
}
.form-control {
    height: 100%;
    padding-bottom: -10px;
}
</style>
<section class="section section--border" id="ToolContent">
  	<div class="page-width">
		<div class="form-section">
         	<div class="section-heading">
            	<h1 class="section-heading__heading heading--1"><?php echo __('Sender Information') ?></h1>
         	</div>
      	</div>
  		<div class="section-block col-md-12">
	  		<form id="form-validate" action="<?php echo $this->getUrl('retailerkittools/index/saveshippingsender') ?>" enctype="multipart/form-data"  accept-charset="UTF-8" method="post">   
	  			<input name="form_key" type="hidden" value="<?php echo $formKey->getFormKey() ?>" />
	    		<div class="form-section col-md-12">
		            <div class="form-header">
		               <h3 class="form-header__heading"><?php echo __('Enter sender information') ?></h3>
		            </div>
		            <div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-4">
								<small class="label" for="input"><?php echo __('First Name') ?></small>
				  				<input type="text" name="sender[first_name]" id="sender_first_name" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','first_name'); ?>" class="form-control required-entry" placeholder="First Name" >
				  			</div>
				  			<div class="form-group col-md-4">
								<small class="label" for="input"><?php echo __('Last Name') ?></small>
				  				<input type="text" name="sender[last_name]" id="sender_last_name" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','last_name'); ?>" class="form-control required-entry" placeholder="Last Name" >
				  			</div>
				  			<div class="form-group col-md-4">
								<small class="label" for="input"><?php echo __('Your email address') ?></small>
				   				<input type="email" name="sender[email]" id="sender_email" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','email'); ?>" class="form-control required-entry validate-email" placeholder="Your email address" >
				   			</div>
				  		</div>
				  	</div>
				  	<div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-8">
								<small class="label" for="input"><?php echo __('Address') ?></small>
				  				<input type="text" name="sender[address]" id="sender_address" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','address'); ?>" class="form-control required-entry" placeholder="Address" >
				  			</div>
				  			<div class="form-group col-md-4">
								<small class="label" for="input"><?php echo __('City') ?></small>
				   				<input type="text" name="sender[city]" id="sender_city" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','city'); ?>" class="form-control required-entry" placeholder="City" >
				   			</div>
				  		</div>
				  	</div>
				  	<div class="section-input-field col-md-12">
				  		<div class="form-input-inline">
				  			<div class="form-group col-md-4">
								<small class="label" for="input"><?php echo __('Zip/postal code') ?></small>
				  				<input type="text" name="sender[zip]" id="sender_zip" value="<?php echo $helper->getRetailerKitToolsConfig('shipping_sender','zipcode'); ?>" class="form-control" placeholder="Zip/postal code" >
				  			</div>
				  			<div class="form-group col-md-4">
								<small class="label" for="input"><?php echo __('Country') ?></small>
				  				<?php echo $this->getCountryHtmlSelect() ?>
				  			</div>
				  			<div class="section-input-field col-md-4">
				   				<div class="input-box">
									<small class="label" for="input"><?php echo __('State/Province') ?></small>
				                	<select id="sender_province_id" name="sender[province_id]" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
					                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
					                </select>
					                <small class="label" for="input"><?php echo __('State/Province') ?></small>
					                <input type="text" id="sender_province" name="sender[province]" value="<?php echo $block->escapeHtml($this->_retailerkittoolHelper->getRetailerKitToolsConfig('shipping_sender','state')) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
				                </div>
						   	</div>
				  		</div>
				   	</div>				   	
		        </div>    		 
				<div class="section-input-field col-md-12">
	      			<div class="form-input-inline">
			  			<div class="form-group col-md-12">
				      		<button name="button" type="submit" class="btn btn-primary btn-lg pull-right" id="Submit"><?php echo __('Save') ?></button>
				      	</div>
				    </div>
				</div>
			</form>
		</div>
  	</div>
</section>
<script type="text/x-magento-init">
    {
        "#sender_country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#sender_province_id",
                "regionInputId": "#sender_province",
                "postcodeId": "#sender_zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script type="text/javascript">
require([
"jquery",
"mage/calendar",
'mage/validation'
], function($){
    var dataForm = $('#form-validate');
    var ignore = null;

    dataForm.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

	$('.form-control').each(function(){
		var el = $(this);
		if(el.val().length > 0){
			el.prev('.label').css('opacity','1');
		}
		el.keyup(function(e) {
			if(el.val().length > 0){
				el.prev('.label').css('opacity','1');
			}else{
				el.prev('.label').css('opacity','0');
			}
		});
	});
});
</script>